/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jser_FHE */

#ifndef _Included_Jser_FHE
#define _Included_Jser_FHE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jser_FHE
 * Method:    service
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Jser_1FHE_service
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
